# Generated by Django 5.0.3 on 2024-03-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('num_of_visiter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel', models.CharField(max_length=100)),
                ('num_of_User', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kind_visit', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('Nationality', models.CharField(max_length=255)),
                ('Birth_date', models.DateField(max_length=255)),
                ('Passport', models.CharField(max_length=20)),
                ('Arrival_date', models.DateField(max_length=300)),
                ('Departure_date', models.DateField(max_length=255)),
                ('Purpose', models.CharField(max_length=200)),
                ('Hotel', models.CharField(max_length=125)),
                ('Id_document', models.ImageField(upload_to='customer/')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
